ifeq ($(CONFIG_DIR_NO), 1)
	obj-y += subdir_/
else 
	ifeq ($(CONFIG_DIR_NO), 2)
		obj-y += subdir_/
	else 
		ifeq ($(CONFIG_DIR_NO), 3)
			obj-y += subdir_/
		else 
			ifeq ($(CONFIG_DIR_NO), 4)
				obj-y += subdir_/
			else 
				ifeq ($(CONFIG_DIR_NO), 5)
					obj-y += subdir_/
				else 
					ifeq ($(CONFIG_DIR_NO), 6)
						obj-y += subdir_/
					else 
						ifeq ($(CONFIG_DIR_NO), 7)
							obj-y += subdir_/
						else 
							ifeq ($(CONFIG_DIR_NO), 8)
								obj-y += subdir_/
							else 
								ifeq ($(CONFIG_DIR_NO), 9)
									obj-y += subdir_/
								else 
									ifeq ($(CONFIG_DIR_NO), 10)
										obj-y += subdir_/
									else 
										ifeq ($(CONFIG_DIR_NO), 11)
											obj-y += subdir_/
										else 
											ifeq ($(CONFIG_DIR_NO), 12)
												obj-y += subdir_/
											else 
												ifeq ($(CONFIG_DIR_NO), 13)
													obj-y += subdir_/
												else 
													ifeq ($(CONFIG_DIR_NO), 14)
														obj-y += subdir_/
													else 
														ifeq ($(CONFIG_DIR_NO), 15)
															obj-y += subdir_/
														else 
															ifeq ($(CONFIG_DIR_NO), 16)
																obj-y += subdir_/
															else 
																ifeq ($(CONFIG_DIR_NO), 17)
																	obj-y += subdir_/
																else 
																	ifeq ($(CONFIG_DIR_NO), 18)
																		obj-y += subdir_/
																	else 
																		ifeq ($(CONFIG_DIR_NO), 19)
																			obj-y += subdir_/
																		else 
																			ifeq ($(CONFIG_DIR_NO), 20)
																				obj-y += subdir_/
																			else 
																				ifeq ($(CONFIG_DIR_NO), 21)
																					obj-y += subdir_/
																				else 
																					ifeq ($(CONFIG_DIR_NO), 22)
																						obj-y += subdir_/
																					else 
																						ifeq ($(CONFIG_DIR_NO), 23)
																							obj-y += subdir_/
																						else 
																							ifeq ($(CONFIG_DIR_NO), 24)
																								obj-y += subdir_/
																							else 
																								ifeq ($(CONFIG_DIR_NO), 25)
																									obj-y += subdir_/
																								else 
																									ifeq ($(CONFIG_DIR_NO), 26)
																										obj-y += subdir_/
																									else 
																										ifeq ($(CONFIG_DIR_NO), 27)
																											obj-y += subdir_/
																										else 
																											ifeq ($(CONFIG_DIR_NO), 28)
																												obj-y += subdir_/
																											else 
																												ifeq ($(CONFIG_DIR_NO), 29)
																													obj-y += subdir_/
																												else 
																													ifeq ($(CONFIG_DIR_NO), 30)
																														obj-y += subdir_/
																													else 
																														ifeq ($(CONFIG_DIR_NO), 31)
																															obj-y += subdir_/
																														else 
																															ifeq ($(CONFIG_DIR_NO), 32)
																																obj-y += subdir_/
																															else 
																																ifeq ($(CONFIG_DIR_NO), 33)
																																	obj-y += subdir_/
																																else 
																																	ifeq ($(CONFIG_DIR_NO), 34)
																																		obj-y += subdir_/
																																	else 
																																		ifeq ($(CONFIG_DIR_NO), 35)
																																			obj-y += subdir_/
																																		else 
																																			ifeq ($(CONFIG_DIR_NO), 36)
																																				obj-y += subdir_/
																																			else 
																																				ifeq ($(CONFIG_DIR_NO), 37)
																																					obj-y += subdir_/
																																				else 
																																					ifeq ($(CONFIG_DIR_NO), 38)
																																						obj-y += subdir_/
																																					else 
																																						ifeq ($(CONFIG_DIR_NO), 39)
																																							obj-y += subdir_/
																																						else 
																																							ifeq ($(CONFIG_DIR_NO), 40)
																																								obj-y += subdir_/
																																							else 
																																								ifeq ($(CONFIG_DIR_NO), 41)
																																									obj-y += subdir_/
																																								else 
																																									ifeq ($(CONFIG_DIR_NO), 42)
																																										obj-y += subdir_/
																																									else 
																																										ifeq ($(CONFIG_DIR_NO), 43)
																																											obj-y += subdir_/
																																										else 
																																											ifeq ($(CONFIG_DIR_NO), 44)
																																												obj-y += subdir_/
																																											else 
																																												ifeq ($(CONFIG_DIR_NO), 45)
																																													obj-y += subdir_/
																																												else 
																																													ifeq ($(CONFIG_DIR_NO), 46)
																																														obj-y += subdir_/
																																													else 
																																														ifeq ($(CONFIG_DIR_NO), 47)
																																															obj-y += subdir_/
																																														else 
																																															ifeq ($(CONFIG_DIR_NO), 48)
																																																obj-y += subdir_/
																																															else 
																																																ifeq ($(CONFIG_DIR_NO), 49)
																																																	obj-y += subdir_/
																																																else 
																																																	ifeq ($(CONFIG_DIR_NO), 50)
																																																		obj-y += subdir_/
																																																	else 
																																																		ifeq ($(CONFIG_DIR_NO), 51)
																																																			obj-y += subdir_/
																																																		else 
																																																			ifeq ($(CONFIG_DIR_NO), 52)
																																																				obj-y += subdir_/
																																																			else 
																																																				ifeq ($(CONFIG_DIR_NO), 53)
																																																					obj-y += subdir_/
																																																				else 
																																																					ifeq ($(CONFIG_DIR_NO), 54)
																																																						obj-y += subdir_/
																																																					else 
																																																						ifeq ($(CONFIG_DIR_NO), 55)
																																																							obj-y += subdir_/
																																																						else 
																																																							ifeq ($(CONFIG_DIR_NO), 56)
																																																								obj-y += subdir_/
																																																							else 
																																																								ifeq ($(CONFIG_DIR_NO), 57)
																																																									obj-y += subdir_/
																																																								endif
																																																							endif
																																																						endif
																																																					endif
																																																				endif
																																																			endif
																																																		endif
																																																	endif
																																																endif
																																															endif
																																														endif
																																													endif
																																												endif
																																											endif
																																										endif
																																									endif
																																								endif
																																							endif
																																						endif
																																					endif
																																				endif
																																			endif
																																		endif
																																	endif
																																endif
																															endif
																														endif
																													endif
																												endif
																											endif
																										endif
																									endif
																								endif
																							endif
																						endif
																					endif
																				endif
																			endif
																		endif
																	endif
																endif
															endif
														endif
													endif
												endif
											endif
										endif
									endif
								endif
							endif
						endif
					endif
				endif
			endif
		endif
	endif
endif
