ifeq ($(CONFIG_DIR_NO), 1)
	obj-y += subdir_/
else 
	ifeq ($(CONFIG_DIR_NO), 2)
		obj-y += subdir_/
	else 
		ifeq ($(CONFIG_DIR_NO), 3)
			obj-y += subdir_/
		else 
			ifeq ($(CONFIG_DIR_NO), 4)
				obj-y += subdir_/
			else 
				ifeq ($(CONFIG_DIR_NO), 5)
					obj-y += subdir_/
				endif
			endif
		endif
	endif
endif
